version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: shope
      POSTGRES_PASSWORD: P@ssw0rd()
      POSTGRES_DB: phone_shope
    networks:
      - app-network
    ports:
      - "5432:5432"  # Mapping to host port for debugging if needed

  api-shope:
    image: phone_shop_api  # Assuming the image is built and tagged as 'api-shope:latest'
    container_name: application
    depends_on:
      - db  # Ensures db starts before the Spring Boot application
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/phone_shope
      SPRING_DATASOURCE_USERNAME: shope
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd()
#      SPRING_LIQUIBASE_URL: jdbc:postgresql://db:5432/phone_shope
#      SPRING_LIQUIBASE_USER: shop
#      SPRING_LIQUIBASE_PASSWORD: P@ssw0rd()
    networks:
      - app-network
    ports:
      - "8081:8081"  # External port for accessing the Spring Boot app

networks:
  app-network:
    driver: bridge
