spring.application.name=phone_shope_Demo
server.port=8081
#database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/phone_shope
spring.datasource.username=shop
spring.datasource.password=P@ssw0rd()
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
#config for swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
#config for Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
